version: '3.8'

services:
  # 1. Service Database MySQL
  mysql-db:
    image: mysql:8.3.0
    container_name: ticketing-db
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "8282:3306"
    volumes:
      # Ánh xạ thư mục chứa file init.sql (Giống hệt tài liệu bài giảng)
      - ./docker/mysql:/docker-entrypoint-initdb.d
      # THÊM DÒNG NÀY VÀO: Lưu trữ vĩnh viễn dữ liệu thật của DB
      - db-data:/var/lib/mysql

  # 2. Service Ứng dụng Spring Boot (Backend)
  ticketing-app:
    build: .
    container_name: ticketing-backend
    ports:
      - "3103:3103"
    depends_on:
      - mysql-db
    environment:
      - SERVER_PORT=3103
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ticketing
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=vps

volumes:
  db-data: